-- !Ups
ALTER TABLE "COMMENTS"
ADD COLUMN "UPDATED_AT" timestamp;

ALTER TABLE "LIKES"
ADD COLUMN "UPDATED_AT" timestamp;

-- !Downs
ALTER TABLE "COMMENTS"
DROP COLUMN "UPDATED_AT";

ALTER TABLE "LIKES"
DROP COLUMN "UPDATED_AT";